services:

    stateless_auth.annotation:
        class: SoftRog\StatelessAuthBundle\Annotations\Driver\AnnotationDriver
        arguments: [@annotation_reader]
        calls:
            - [setValidator, [@stateless_auth.validator]]
            - [setRequestStack, [@request_stack]]
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

