services:
    stateless_auth.generator:
        class: SoftRog\StatelessAuthBundle\Authentication\Generator
        calls:
            - [setContainer, ["@service_container"]]

    stateless_auth.authenticator:
        class: SoftRog\StatelessAuthBundle\Authentication\Authenticator
        calls:
            - [setContainer, ["@service_container"]]

    stateless_auth.annotation:
        class: SoftRog\StatelessAuthBundle\Annotations\Driver\AnnotationDriver
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
        arguments: [@annotation_reader, "@stateless_auth.authenticator"]

